SMS/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/',include('facultyapp.urls',namespace='facultyapp')),
    path('studentapp/',include('studentapp.urls',namespace='studentapp')),

]

facultyapp/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name = 'facultyapp'

urlpatterns = [
    path('', views.FacultyHomePage, name='FacultyHomePage'),

    # path('blog_list/', views.blog_home, name='blog_list'),
    # path('blog/<slug:slug>/', views.blog_home, name='blog_detail'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('<int:pk>/delete/', views.delete_task, name='delete'),
    path('add_course/',views.add_course,name='add_course'),
    path('view_student_list/',views.view_student_list,name='view_student_list'),
    path('post_marks/',views.post_marks,name='post_marks'),

]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style>
        .navbar {
            background-color: #FD8A8A !important;
        }
    </style>

</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_blog' %} ">Blog</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">Add course</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View Student List</a>
        </li>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">Post Marks</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>

        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<!--<style>-->
<!--        .navbar {-->
<!--            background-color: red !important;-->
<!--        }-->
<!--    </style>-->

</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add student</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception Handling</a></li>
            <li><a class="dropdown-item" href="{% url 'randompagecall' %}">Generate OTP</a></li>
            <li><a class="dropdown-item" href="{% url 'calculatorlogic' %}">Calcualator</a></li>
            <li><a class="dropdown-item" href="{% url 'add_task' %}">To Do List</a></li>
              <li><a class="dropdown-item" href="{% url 'datetime_view' %}">Date Time Example</a></li>
              <li><a class="dropdown-item" href="{% url 'upload_file' %}">Generate chart</a></li>
              <li><a class="dropdown-item" href="{% url 'submit_feedback' %}">Submit Feedback</a></li>
              <li><a class="dropdown-item" href="{% url 'contact_list' %}">Contacts Manage</a></li>



          </ul>
        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style>
        .navbar {
            background-color: #A8D1D1 !important;
        }
    </style>

</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add student</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>

        </li>
      </ul>
    </div>
  <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>